# Generated by Django 5.0.3 on 2024-03-20 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasksOrganizerApp', '0002_rename_finaldate_course_endingdate_task_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='hour',
        ),
    ]
