# Generated by Django 5.0.3 on 2024-03-20 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasksOrganizerApp', '0003_remove_task_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(),
        ),
    ]
