# Generated by Django 5.0.3 on 2024-03-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasksOrganizerApp', '0004_alter_task_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='hour',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(),
        ),
    ]
