# Generated by Django 5.0.3 on 2024-03-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasksOrganizerApp', '0005_task_hour_alter_task_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
